<a href="https://colab.research.google.com/github/atomiceltaweel/PensionBenefit_Calculator/blob/master/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# https://www.openml.org/d/42876
import os
import pandas as pd

# Workers Compensation dataset, see
# https://www.openml.org/d/42876
if not os.path.exists("workers_compensation.parquet"):
    df = pd.DataFrame(df_origin$data)
    df.to_parquet("workers_compensation.parquet")
else:
    df = pd.read_parquet("workers_compensation.parquet")
```

SyntaxError: ignored

In [26]:
df = pd.DataFrame(df_origin$data)

SyntaxError: ignored

In [11]:
import openml
import pandas as pd
from openml.datasets import edit_dataset, fork_dataset, get_dataset

ModuleNotFoundError: ignored

In [ ]:
df_origin = openml.datasets.get_dataset(42876)
df = pd.DataFrame(df_origin.data)

In [36]:
# This is done based on the dataset ID.
dataset = openml.datasets.get_dataset(42876)

# Print a summary
print(
    f"This is dataset '{dataset.name}', the target feature is "
    f"'{dataset.default_target_attribute}'"
)
print(f"URL: {dataset.url}")
print(dataset.description[:500])

This is dataset 'WorkersCompensation', the target feature is 'UltimateIncurredClaimCost'
URL: https://api.openml.org/data/v1/download/22045494/WorkersCompensation.arff
This dataset describes 100,000 realistic, synthetically generated worker compensation insurance claims. Along the ultimate financial losses, each claim is described by the initial case estimate, date of accident and reporting date, a text describing the accident and demographic info on the worker.

The dataset was kindly created and provided by Colin Priest. While similar, it is not identical to the dataset used in www.kaggle.com/c/actuarial-loss-estimation.

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:438: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

In [37]:
eeg, *_ = dataset.get_data()
eeg

,DateTimeOfAccident,DateReported,Age,Gender,MaritalStatus,DependentChildren,DependentsOther,WeeklyPay,PartTimeFullTime,HoursWorkedPerWeek,DaysWorkedPerWeek,ClaimDescription,InitialCaseEstimate,UltimateIncurredClaimCost
0,2005-01-13 09:00:00,2005-01-24,45,M,S,0,0,500.0,F,38.0,5,MOVING DISC STRAINED RIGHT SHOULDER,9500.0,102.39
1,1994-09-28 15:00:00,1994-10-17,40,M,M,0,0,283.0,F,38.0,5,BOILING WATER CAME FROM TRUCK STRAIN RIGHT WRIST,3000.0,1451.00
2,1991-11-11 14:00:00,1992-04-16,19,F,S,0,0,0.0,F,0.0,5,SLIPPED ON UNEVEN DOOR FRACTURE RIGHT HAND,250.0,48.00
3,2004-08-30 08:00:00,2004-10-21,18,F,U,0,0,373.0,P,2.0,4,HIT FROM BENCH JACK PUNCTURE WOUND RIGHT FOOT,1000.0,492.88
4,1996-11-23 09:00:00,1996-12-09,34,M,M,0,0,200.0,F,6.0,5,BENDING DOWN NERVE OF CAR,400.0,191.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1988-01-04 09:00:00,1988-02-22,57,M,M,0,0,420.0,F,40.0,5,KNEE ON SLIPPED JARRED INJURY TO ON,3900.0,638.40
99996,2001-10-03 12:00:00,2001-11-19,19,M,S,0,0,200.0,F,38.0,5,TURNED ONSET AND STRAIN LOWER BACK,17000.0,4112.82
99997,1994-05-30 01:00:00,1995-01-06,41,M,M,0,0,0.0,F,0.0,5,GETTING HIT BROKE SAW CUT LOWER BACK,3500.0,430.50
99998,1994-05-20 09:00:00,1994-06-13,19,M,S,0,0,356.0,F,38.0,5,SLIPPED WHILST USING KNIFE CRUSH IN RIGHT ELBOW,7500.0,3513.00
99999,1999-07-03 06:00:00,1999-07-28,28,M,S,0,0,200.0,F,38.0,5,FINGERS SLIPPED INTO BRUISING BONE,15950.0,683.00

In [38]:
X, y, categorical_indicator, attribute_names = dataset.get_data(
    target=dataset.default_target_attribute
)
print(X.head())
print(X.info())

    DateTimeOfAccident DateReported  Age Gender MaritalStatus  \
0  2005-01-13 09:00:00   2005-01-24   45      M             S
1  1994-09-28 15:00:00   1994-10-17   40      M             M
2  1991-11-11 14:00:00   1992-04-16   19      F             S
3  2004-08-30 08:00:00   2004-10-21   18      F             U
4  1996-11-23 09:00:00   1996-12-09   34      M             M

   DependentChildren  DependentsOther  WeeklyPay PartTimeFullTime  \
0                  0                0      500.0                F
1                  0                0      283.0                F
2                  0                0        0.0                F
3                  0                0      373.0                P
4                  0                0      200.0                F

   HoursWorkedPerWeek  DaysWorkedPerWeek  \
0                38.0                  5
1                38.0                  5
2                 0.0                  5
3                 2.0                  4
4                 6.0                  5

                                   ClaimDescription  InitialCaseEstimate
0               MOVING DISC STRAINED RIGHT SHOULDER               9500.0
1  BOILING WATER CAME FROM TRUCK STRAIN RIGHT WRIST               3000.0
2        SLIPPED ON UNEVEN DOOR FRACTURE RIGHT HAND                250.0
3     HIT FROM BENCH JACK PUNCTURE WOUND RIGHT FOOT               1000.0
4                         BENDING DOWN NERVE OF CAR                400.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   DateTimeOfAccident   100000 non-null  object
 1   DateReported         100000 non-null  object
 2   Age                  100000 non-null  uint8
 3   Gender               100000 non-null  object
 4   MaritalStatus        100000 non-null  object
 5   DependentChildren    100000 non-null  uint8
 6   DependentsOther      100000 non-null  uint8
 7   WeeklyPay            100000 non-null  float64
 8   PartTimeFullTime     100000 non-null  object
 9   HoursWorkedPerWeek   100000 non-null  float64
 10  DaysWorkedPerWeek    100000 non-null  uint8
 11  ClaimDescription     100000 non-null  object
 12  InitialCaseEstimate  100000 non-null  float64
dtypes: float64(3), object(6), uint8(4)
memory usage: 7.2+ MB
None

In [41]:
 target=dataset.default_target_attribute
 target

'UltimateIncurredClaimCost'

In [43]:
print(y.head())
print(y.info())

0     102.39
1    1451.00
2      48.00
3     492.88
4     191.00
Name: UltimateIncurredClaimCost, dtype: float64
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: UltimateIncurredClaimCost
Non-Null Count   Dtype
--------------   -----
100000 non-null  float64
dtypes: float64(1)
memory usage: 781.4 KB
None

In [ ]:
pip install openml

In [ ]:
from sklearn import ensemble
from openml import tasks, flows, Runs

task = tasks.get_task(3954)
clf = ensemble.RandomForestClassifier()
flow = flows.sklearn_to_flow(clf)
run = runs.run_flow_on_task(task, flow)
result = run.publish()

In [13]:
import openml
import pandas as pd
from openml.datasets import edit_dataset, fork_dataset, get_dataset

In [17]:
# https://www.openml.org/d/42876
import os
import pandas as pd

# Workers Compensation dataset, see
# https://www.openml.org/d/42876
if not os.path.exists("workers_compensation.parquet"):
    library(OpenML)
    df_origin = getOMLDataSet(data.id=42876L)
    df = pd.DataFrame(df_origin$data)
    df.to_parquet("workers_compensation.parquet")
else:
    df = pd.read_parquet("workers_compensation.parquet")
```

SyntaxError: ignored